const $=id=>document.getElementById(id);
let user=null,activeChatId=null,chats=[],register=false,storage=null;
const auth=$("auth"),app=$("app"),authForm=$("authForm"),authTitle=$("authTitle"),authSub=$("authSub"),nameI=$("name"),authBtn=$("authBtn"),toggle=$("toggleAuth"),google=$("googleBtn"),err=$("authError");
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function plain(v){return esc(String(v??"")).replace(/\*\*(.*?)\*\*/g,"$1").replace(/`([^`]*)`/g,"$1")}
function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem("cds-theme",t)}
function initTheme(){let t=localStorage.getItem("cds-theme")||"system";setTheme(t)}
toggle.onclick=()=>{register=!register;nameI.style.display=register?"block":"none";authTitle.textContent=register?"Create your account":"Welcome back";authSub.textContent=register?"Your private clinical evidence workspace starts here.":"Sign in to your evidence-grounded hypertension assistant.";authBtn.textContent=register?"Create account":"Continue";toggle.textContent=register?"Already have an account? Sign in":"Create an account";err.textContent=""};
google.onclick=()=>{window.location.assign("/api/auth/google")};
authForm.onsubmit=async e=>{e.preventDefault();err.textContent="";try{let r=await fetch(register?"/api/auth/register":"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(register?{name:nameI.value,email:$("email").value,password:$("password").value}:{email:$("email").value,password:$("password").value})});let d=await r.json();if(!r.ok)throw Error(d.detail||"Authentication failed");await boot()}catch(x){err.textContent=x.message}};
async function api(url,opt={}){let r=await fetch(url,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});let d=await r.json();if(!r.ok)throw Error(d.detail||"Request failed");return d}
async function boot(){initTheme();const qs=new URLSearchParams(location.search);if(qs.get("auth_error"))err.textContent=qs.get("auth_error");try{let d=await api("/api/auth/me");user=d.user;storage=d.storage;auth.classList.add("hidden");app.classList.remove("hidden");$("userName").textContent=user.name;$("userEmail").textContent=user.email;$("avatar").textContent=user.name[0].toUpperCase();await loadHistory();updateStorage(storage);health()}catch(e){auth.classList.remove("hidden");app.classList.add("hidden")}}
async function loadHistory(){let d=await api("/api/history");chats=d.conversations;renderHistory();if(chats.length){activeChatId=chats[0].id;await loadChat(activeChatId)}else await newChat()}
function renderHistory(){$("history").innerHTML=chats.map(c=>`<button class="history-item ${c.id===activeChatId?"active":""}" data-id="${esc(c.id)}"><span class="history-dot"></span><span class="history-label">${esc(c.title)}</span></button>`).join("");document.querySelectorAll(".history-item").forEach(b=>b.onclick=()=>loadChat(b.dataset.id))}
async function newChat(){try{let d=await api("/api/history",{method:"POST"});activeChatId=d.id;chats.unshift({id:d.id,title:d.title});renderHistory();$("chat").innerHTML=`<div class="welcome"><div class="welcome-icon">✚</div><h2>Welcome, ${esc(user.name)}</h2><p>Ask an Adult Hypertension question grounded in approved evidence.</p></div>`}catch(e){alert(e.message)}}
$("newChat").onclick=newChat;
async function loadChat(id){activeChatId=id;renderHistory();let d=await api("/api/history/"+id);$("chat").innerHTML="";d.messages.forEach(m=>appendMessage(m.role,m.content,m.answer_json?JSON.parse(m.answer_json):null,m.id));$("chat").scrollTop=$("chat").scrollHeight}
function renderTable(t){if(!t||!Array.isArray(t.headers)||!t.headers.length||!Array.isArray(t.rows)||!t.rows.length)return "";return `<div class="table-wrap"><table><thead><tr>${t.headers.map(h=>`<th>${plain(h)}</th>`).join("")}</tr></thead><tbody>${t.rows.map(row=>`<tr>${t.headers.map((_,i)=>`<td>${plain(row[i]??"")}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function renderResult(r,mid,cid){let missing=(r.missing_information||[]).filter(Boolean);let missingHtml=missing.length?`<div class="partial-note"><strong>What I could not establish from the approved evidence:</strong><ul>${missing.map(x=>`<li>${plain(x)}</li>`).join("")}</ul></div>`:"";let html=`<div class="answer-status">${r.status==="answered"?"Grounded answer":r.status==="safety_refusal"?"Scope & safety boundary":r.status==="clarification_needed"?"Clarification needed":"Insufficient evidence"}</div><div class="answer-text">${plain(r.recommendation||"")}</div>${missingHtml}${renderTable(r.table)}`;
if(r.status==="answered"&&r.supporting_evidence?.length)html+=`<div class="sources"><b>Sources</b>${(r.source_details||[]).map((s,i)=>`<button class="source-card source-button" data-mid="${esc(mid)}" data-cid="${esc(cid)}"><strong>${plain(s.document_name||"Approved source")}</strong><span>${plain(s.section||"")} · Page ${plain(s.page_number||"")}</span><em>View the evidence used ›</em></button>`).join("")}</div>`;
return html}
function appendMessage(role,content,result,mid){let a=document.createElement("article");a.className="message "+(role==="user"?"user-message":"assistant-message");if(role==="user"){a.innerHTML=`<div class="bubble user-bubble">${esc(content)}</div>`}else{a.innerHTML=`<div class="assistant-avatar">AI</div><div class="assistant-body"><div class="assistant-bubble">${result?renderResult(result,mid,activeChatId):esc(content)}</div><div class="message-actions" data-mid="${esc(mid||"")}"><button data-feedback="up">♡ Helpful</button><button data-feedback="down">♧ Not helpful</button><button data-reply>↩ Reply</button><button data-copy>Copy</button></div></div>`}$("chat").appendChild(a);a.querySelectorAll("[data-feedback]").forEach(b=>b.onclick=async()=>{if(!mid)return;await api(`/api/messages/${mid}/feedback`,{method:"POST",body:JSON.stringify({feedback:b.dataset.feedback})});b.textContent=b.dataset.feedback==="up"?"✓ Helpful":"✓ Not helpful"});a.querySelector("[data-reply]")?.addEventListener("click",()=>{$("question").value=`About this answer: ${result?.recommendation||content}\n\n`;$("question").focus()});a.querySelector("[data-copy]")?.addEventListener("click",()=>navigator.clipboard.writeText(a.querySelector(".assistant-bubble").innerText));a.querySelectorAll(".source-button").forEach(b=>b.onclick=()=>openSource(b.dataset.cid,b.dataset.mid));$("chat").scrollTop=$("chat").scrollHeight}
async function openSource(cid,mid){try{let d=await api(`/api/source/${cid}/${mid}`);$("sourceContent").innerHTML=(d.sources||[]).map(s=>`<div class="source-detail"><h3>${plain(s.document_name)}</h3><p><b>${plain(s.section||"")}</b> · Page ${plain(s.page_number||"")}</p><blockquote>${plain(s.excerpt||"")}</blockquote>${s.source_url?`<a target="_blank" rel="noopener noreferrer" href="${esc(s.source_url)}">Open source document ↗</a>`:"<small>Approved source document available in the project's evidence set.</small>"}</div>`).join("");$("sourceModal").classList.remove("hidden")}catch(e){alert(e.message)}}
async function ask(){let q=$("question").value.trim();if(!q)return;if(!activeChatId)await newChat();appendMessage("user",q);$("question").value="";$("askButton").disabled=true;$("status").textContent="Retrieving strongest evidence…";try{let r=await api("/api/retrieve",{method:"POST",body:JSON.stringify({question:q,top_k:1,strategy:"hybrid",config:"B_850_150",rerank:true})});if(r.pre_result){$("status").textContent="Preparing response…";let a=await api("/api/answer",{method:"POST",body:JSON.stringify({retrieval_id:r.retrieval_id,question:q,conversation_id:activeChatId})});appendMessage("assistant","",a.result,a.assistant_message_id);await loadHistory();activeChatId=a.conversation_id;renderHistory();return}if(!r.evidence.length)throw Error("No supporting evidence was found.");$("status").textContent="Generating grounded answer…";let a=await api("/api/answer",{method:"POST",body:JSON.stringify({retrieval_id:r.retrieval_id,question:q,conversation_id:activeChatId})});appendMessage("assistant","",a.result,a.assistant_message_id);await loadHistory();activeChatId=a.conversation_id;renderHistory();await refreshStorage()}catch(e){appendMessage("assistant",e.message,{status:"insufficient_evidence",recommendation:e.message,confidence:"Insufficient Evidence"})}finally{$("askButton").disabled=false;$("status").textContent="Safety guardrails · Grounded evidence"}}
$("askButton").onclick=ask;$("question").onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")ask()};document.querySelectorAll(".example").forEach(b=>b.onclick=()=>{$("question").value=b.textContent;ask()});
$("logout").onclick=async()=>{await api("/api/auth/logout",{method:"POST"});location.reload()};$("menuButton").onclick=()=>$("sidebar").classList.toggle("open");
$("mic").onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("status").textContent="Voice input is not supported in this browser.";return}let r=new SR();r.lang="en-US";r.interimResults=false;r.onstart=()=>{$("mic").classList.add("recording");$("status").textContent="Listening…"};r.onresult=e=>$("question").value=e.results[0][0].transcript;r.onend=()=>{$("mic").classList.remove("recording");$("status").textContent="Voice captured — press send."};r.start()};
async function refreshStorage(){try{let d=await api("/api/settings/storage");storage=d;updateStorage(d)}catch{}}
function updateStorage(d){if(!d)return;$("storageText").textContent=`${formatBytes(d.used_bytes)} of ${formatBytes(d.limit_bytes)} used`;$("storagePercent").textContent=`${d.used_percent}%`;$("storageBar").style.width=Math.min(100,d.used_percent)+"%";$("storageWarning").textContent=d.full?"Your chat storage is full. Manage storage to continue saving new history.":d.warning?"Your chat storage is almost full. Consider managing old conversations.":"";$("manageStorage").classList.toggle("hidden",!d.warning)}
function formatBytes(n){if(n<1024)return n+" B";if(n<1048576)return (n/1024).toFixed(0)+" KB";return (n/1048576).toFixed(1)+" MB"}
$("settings").onclick=async()=>{await refreshStorage();$("settingsModal").classList.remove("hidden")};$("closeSettings").onclick=()=>$("settingsModal").classList.add("hidden");$("closeSource").onclick=()=>$("sourceModal").classList.add("hidden");
document.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));
$("manageStorage").onclick=async()=>{if(!confirm("Delete all of your chat history? This cannot be undone."))return;await api("/api/settings/storage",{method:"DELETE"});$("settingsModal").classList.add("hidden");activeChatId=null;await loadHistory();await refreshStorage()};
async function health(){try{let d=await api("/api/health");$("health").textContent=d.index_ready?"Ready":"Index needed";$("health").classList.toggle("ready",d.index_ready)}catch{}}
boot();
